############################################################
#
# 开发环境 端口 8088
#
############################################################
server:
  port: 8088


############################################################
#
# 配置数据源信息
#
############################################################
spring:
  datasource:                                     # 数据源的相关配置
    url: jdbc:mysql://localhost:3306/foodie-shop-dev?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=GMT%2B8&useSSL=false
    password: mysql123


############################################################
#
# mybatis 配置
#
############################################################
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl   # 控制台输出日志文件（输出SQL调用语句）
