############################################################
#
# 生产环境 端口 80
#
############################################################
server:
  port: 80

spring:
  datasource:                                     # 数据源的相关配置
    url: jdbc:mysql://192.168.197.128:3306/foodie-shop-dev?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=GMT%2B8&useSSL=false
    password: admin123